-- Global seed. `supabase db push` does not run seed.sql against a remote project,
-- so the shipped defaults have to be a numbered migration.

-- ── 17 categories, ordered like the aisles of an Israeli supermarket ──
insert into public.default_categories (key, name, emoji, color, position) values
  ('produce',    'פירות וירקות',        '🥬', 'green',   1),
  ('bakery',     'לחם ומאפים',          '🥖', 'amber',   2),
  ('dairy',      'חלב, ביצים וגבינות',  '🥛', 'sky',     3),
  ('meat',       'בשר, עוף ודגים',      '🍗', 'red',     4),
  ('frozen',     'קפואים',              '🧊', 'cyan',    5),
  ('canned',     'שימורים ומזון יבש',   '🥫', 'orange',  6),
  ('grains',     'אורז, פסטה וקטניות',  '🍚', 'yellow',  7),
  ('condiments', 'שמן, רטבים ותבלינים', '🫒', 'lime',    8),
  ('coffee',     'קפה, תה וממרחים',     '☕', 'stone',   9),
  ('snacks',     'חטיפים ומתוקים',      '🍫', 'pink',   10),
  ('drinks',     'משקאות',              '🥤', 'blue',   11),
  ('baby',       'מוצרי תינוקות',       '🍼', 'rose',   12),
  ('cleaning',   'ניקיון וכביסה',       '🧼', 'teal',   13),
  ('pharma',     'טואלטיקה ופארם',      '🧴', 'violet', 14),
  ('household',  'כלי בית וחד־פעמי',    '🧻', 'slate',  15),
  ('pets',       'חיות מחמד',           '🐾', 'emerald',16),
  ('other',      'אחר',                 '🛒', 'zinc',   17)
on conflict (key) do nothing;

-- ── Global product catalog ──
insert into public.catalog_items (household_id, name, aliases, category_key, default_unit, emoji, is_staple) values
  -- produce
  (null, 'עגבניות',            array['עגבניה','עגבנייה'],            'produce', 'ק״ג', '🍅', true),
  (null, 'עגבניות שרי',        array['שרי'],                          'produce', 'חבילה', '🍅', false),
  (null, 'מלפפונים',           array['מלפפון'],                       'produce', 'ק״ג', '🥒', true),
  (null, 'בצל',                array['בצלים','בצל יבש'],              'produce', 'ק״ג', '🧅', true),
  (null, 'בצל סגול',           array[]::text[],                       'produce', 'ק״ג', '🧅', false),
  (null, 'שום',                array['ראש שום'],                      'produce', 'יח׳', '🧄', true),
  (null, 'תפוחי אדמה',         array['תפוד','תפודים','תפוח אדמה'],    'produce', 'ק״ג', '🥔', true),
  (null, 'בטטה',               array['בטטות'],                        'produce', 'ק״ג', '🍠', false),
  (null, 'גזר',                array['גזרים'],                        'produce', 'ק״ג', '🥕', true),
  (null, 'פלפל אדום',          array['פלפל'],                         'produce', 'ק״ג', '🫑', true),
  (null, 'פלפל צהוב',          array[]::text[],                       'produce', 'ק״ג', '🫑', false),
  (null, 'פלפל ירוק',          array[]::text[],                       'produce', 'ק״ג', '🫑', false),
  (null, 'חסה',                array['חסה ערבית','חסה אייסברג'],      'produce', 'יח׳', '🥬', true),
  (null, 'כרוב',               array['כרוב לבן'],                     'produce', 'יח׳', '🥬', false),
  (null, 'כרוב סגול',          array[]::text[],                       'produce', 'יח׳', '🥬', false),
  (null, 'כרובית',             array[]::text[],                       'produce', 'יח׳', '🥦', false),
  (null, 'ברוקולי',            array[]::text[],                       'produce', 'יח׳', '🥦', false),
  (null, 'קישואים',            array['קישוא'],                        'produce', 'ק״ג', '🥒', false),
  (null, 'חציל',               array['חצילים'],                       'produce', 'ק״ג', '🍆', false),
  (null, 'דלעת',               array[]::text[],                       'produce', 'ק״ג', '🎃', false),
  (null, 'סלרי',               array['קלרי'],                         'produce', 'יח׳', '🥬', false),
  (null, 'פטרוזיליה',          array['פטרוזליה'],                     'produce', 'יח׳', '🌿', true),
  (null, 'כוסברה',             array[]::text[],                       'produce', 'יח׳', '🌿', true),
  (null, 'שמיר',               array[]::text[],                       'produce', 'יח׳', '🌿', false),
  (null, 'נענע',               array['מנטה'],                         'produce', 'יח׳', '🌿', false),
  (null, 'בזיליקום',           array['בזיליקום טרי'],                 'produce', 'יח׳', '🌿', false),
  (null, 'תרד',                array['תרד טרי'],                      'produce', 'חבילה', '🥬', false),
  (null, 'פטריות',             array['פטריות שמפיניון'],              'produce', 'חבילה', '🍄', false),
  (null, 'תפוחים',             array['תפוח','תפוח עץ'],               'produce', 'ק״ג', '🍎', true),
  (null, 'בננות',              array['בננה'],                         'produce', 'ק״ג', '🍌', true),
  (null, 'תפוזים',             array['תפוז'],                         'produce', 'ק״ג', '🍊', false),
  (null, 'קלמנטינות',          array['קלמנטינה','מנדרינה'],           'produce', 'ק״ג', '🍊', false),
  (null, 'לימונים',            array['לימון'],                        'produce', 'ק״ג', '🍋', true),
  (null, 'אבוקדו',             array[]::text[],                       'produce', 'ק״ג', '🥑', true),
  (null, 'ענבים',              array['ענב'],                          'produce', 'ק״ג', '🍇', false),
  (null, 'אבטיח',              array[]::text[],                       'produce', 'יח׳', '🍉', false),
  (null, 'מלון',               array[]::text[],                       'produce', 'יח׳', '🍈', false),
  (null, 'אפרסקים',            array['אפרסק'],                        'produce', 'ק״ג', '🍑', false),
  (null, 'נקטרינות',           array['נקטרינה'],                      'produce', 'ק״ג', '🍑', false),
  (null, 'שזיפים',             array['שזיף'],                         'produce', 'ק״ג', '🍑', false),
  (null, 'אגסים',              array['אגס'],                          'produce', 'ק״ג', '🍐', false),
  (null, 'תותים',              array['תות','תות שדה'],                'produce', 'חבילה', '🍓', false),
  (null, 'רימונים',            array['רימון'],                        'produce', 'ק״ג', '🍎', false),
  (null, 'תמרים',              array['תמר','מג׳הול'],                 'produce', 'חבילה', '🌴', false),
  (null, 'ג׳ינג׳ר',            array['זנגביל'],                       'produce', 'ק״ג', '🫚', false),

  -- bakery
  (null, 'לחם אחיד פרוס',      array['לחם','לחם שחור','פרוס'],        'bakery', 'יח׳', '🍞', true),
  (null, 'לחם לבן',            array['לחם קל'],                       'bakery', 'יח׳', '🍞', false),
  (null, 'לחם מקמח מלא',       array['לחם מלא'],                      'bakery', 'יח׳', '🍞', false),
  (null, 'לחמניות',            array['לחמניה','לחמנייה'],             'bakery', 'חבילה', '🥐', true),
  (null, 'פיתות',              array['פיתה'],                         'bakery', 'חבילה', '🫓', true),
  (null, 'לאפה',               array['לאפות'],                        'bakery', 'חבילה', '🫓', false),
  (null, 'חלה',                array['חלות'],                         'bakery', 'יח׳', '🍞', false),
  (null, 'בגט',                array['באגט'],                         'bakery', 'יח׳', '🥖', false),
  (null, 'קרואסונים',          array['קרואסון'],                      'bakery', 'חבילה', '🥐', false),
  (null, 'רוגלך',              array['רוגלה'],                        'bakery', 'חבילה', '🥐', false),
  (null, 'בורקס',              array['בורקסים'],                      'bakery', 'חבילה', '🥟', false),
  (null, 'מצות',               array['מצה'],                          'bakery', 'חבילה', '🫓', false),
  (null, 'טורטיות',            array['טורטיה','ראפ'],                 'bakery', 'חבילה', '🌯', false),
  (null, 'עוגיות חמאה',        array[]::text[],                       'bakery', 'חבילה', '🍪', false),
  (null, 'עוגת שמרים',         array[]::text[],                       'bakery', 'יח׳', '🍰', false),
  (null, 'קרקרים',             array['קרקר'],                         'bakery', 'חבילה', '🍘', false),
  (null, 'פריכיות אורז',       array['פריכיות'],                      'bakery', 'חבילה', '🍘', false),
  (null, 'בייגלה',             array['ביגלה'],                        'bakery', 'חבילה', '🥨', false),
  (null, 'פיצה קפואה',         array[]::text[],                       'bakery', 'יח׳', '🍕', false),
  (null, 'קובנייה',            array[]::text[],                       'bakery', 'יח׳', '🍞', false),

  -- dairy
  (null, 'חלב 3%',             array['חלב','חלב תנובה'],              'dairy', 'ליטר', '🥛', true),
  (null, 'חלב 1%',             array['חלב דל שומן'],                  'dairy', 'ליטר', '🥛', false),
  (null, 'חלב סויה',           array[]::text[],                       'dairy', 'ליטר', '🥛', false),
  (null, 'חלב שקדים',          array['משקה שקדים'],                   'dairy', 'ליטר', '🥛', false),
  (null, 'חלב עמיד',           array['חלב ארוך'],                     'dairy', 'ליטר', '🥛', false),
  (null, 'ביצים L',            array['ביצים','תבנית ביצים'],          'dairy', 'תבנית', '🥚', true),
  (null, 'ביצים אורגניות',     array[]::text[],                       'dairy', 'תבנית', '🥚', false),
  (null, 'קוטג׳ 5%',           array['קוטג','קוטג׳'],                 'dairy', 'יח׳', '🧀', true),
  (null, 'לבנה 5%',            array['לבנה'],                         'dairy', 'יח׳', '🧀', true),
  (null, 'גבינה לבנה 5%',      array['גבינה לבנה'],                   'dairy', 'יח׳', '🧀', true),
  (null, 'גבינה צהובה',        array['עמק','גבינה פרוסה'],            'dairy', 'חבילה', '🧀', true),
  (null, 'גבינת שמנת',         array['פילדלפיה','ממרח גבינה'],        'dairy', 'יח׳', '🧀', false),
  (null, 'מוצרלה',             array['מוצרלה מגורדת'],                'dairy', 'חבילה', '🧀', false),
  (null, 'פטה',                array['גבינת פטה','בולגרית'],          'dairy', 'יח׳', '🧀', false),
  (null, 'פרמזן',              array['פרמזן מגורד'],                  'dairy', 'חבילה', '🧀', false),
  (null, 'שמנת חמוצה',         array['שמנת'],                         'dairy', 'יח׳', '🥛', false),
  (null, 'שמנת מתוקה',         array['שמנת להקצפה'],                  'dairy', 'יח׳', '🥛', false),
  (null, 'חמאה',               array['חמאת חלב'],                     'dairy', 'יח׳', '🧈', true),
  (null, 'מרגרינה',            array['תעם'],                          'dairy', 'יח׳', '🧈', false),
  (null, 'יוגורט טבעי',        array['יוגורט'],                       'dairy', 'יח׳', '🥣', true),
  (null, 'יוגורט יווני',       array[]::text[],                       'dairy', 'יח׳', '🥣', false),
  (null, 'דנונה',              array['יוגורט לילדים'],                'dairy', 'חבילה', '🥣', false),
  (null, 'מילקי',              array['מעדן שוקולד'],                  'dairy', 'חבילה', '🍮', false),
  (null, 'אשל',                array[]::text[],                       'dairy', 'יח׳', '🥣', false),
  (null, 'ריקוטה',             array[]::text[],                       'dairy', 'יח׳', '🧀', false),
  (null, 'שוקו בשקית',         array['שוקו'],                         'dairy', 'חבילה', '🥛', false),
  (null, 'פודינג',             array[]::text[],                       'dairy', 'חבילה', '🍮', false),
  (null, 'גבינת עיזים',        array['גבינה מעיזים'],                 'dairy', 'יח׳', '🧀', false),
  (null, 'קרם חלבי לבישול',    array['קרם קוקינג'],                   'dairy', 'יח׳', '🥛', false),
  (null, 'חלב מרוכז מתוק',     array[]::text[],                       'dairy', 'יח׳', '🥛', false),

  -- meat
  (null, 'חזה עוף',            array['עוף','פילה עוף'],               'meat', 'ק״ג', '🍗', true),
  (null, 'שוקיים עוף',         array['שוקיים','שוק עוף'],             'meat', 'ק״ג', '🍗', false),
  (null, 'כרעיים עוף',         array['כרעיים'],                       'meat', 'ק״ג', '🍗', false),
  (null, 'כנפיים עוף',         array['כנפיים'],                       'meat', 'ק״ג', '🍗', false),
  (null, 'עוף שלם',            array[]::text[],                       'meat', 'יח׳', '🍗', false),
  (null, 'שניצל עוף',          array['שניצל'],                        'meat', 'ק״ג', '🍗', true),
  (null, 'טחון בקר',           array['בשר טחון','טחון'],              'meat', 'ק״ג', '🥩', true),
  (null, 'אנטריקוט',           array[]::text[],                       'meat', 'ק״ג', '🥩', false),
  (null, 'פילה בקר',           array[]::text[],                       'meat', 'ק״ג', '🥩', false),
  (null, 'אסאדו',              array['אסדו'],                         'meat', 'ק״ג', '🥩', false),
  (null, 'צלי כתף',            array['כתף בקר'],                      'meat', 'ק״ג', '🥩', false),
  (null, 'קבב',                array['קבבים'],                        'meat', 'ק״ג', '🍢', false),
  (null, 'נקניקיות',           array['נקניקיה','נקניקייה'],           'meat', 'חבילה', '🌭', true),
  (null, 'פסטרמה',             array['פסטרמה הודו'],                  'meat', 'חבילה', '🥓', true),
  (null, 'נקניק',              array['סלמי'],                         'meat', 'חבילה', '🥓', false),
  (null, 'המבורגר',            array['המבורגרים'],                    'meat', 'חבילה', '🍔', false),
  (null, 'כבד עוף',            array['כבדי עוף'],                     'meat', 'ק״ג', '🍗', false),
  (null, 'הודו',               array['חזה הודו'],                     'meat', 'ק״ג', '🦃', false),
  (null, 'סלמון',              array['פילה סלמון'],                   'meat', 'ק״ג', '🐟', true),
  (null, 'דניס',               array[]::text[],                       'meat', 'ק״ג', '🐟', false),
  (null, 'לברק',               array[]::text[],                       'meat', 'ק״ג', '🐟', false),
  (null, 'אמנון',              array['מושט'],                         'meat', 'ק״ג', '🐟', false),
  (null, 'פילה בקלה',          array['בקלה'],                         'meat', 'ק״ג', '🐟', false),
  (null, 'קציצות דג',          array['גפילטע'],                       'meat', 'חבילה', '🐟', false),
  (null, 'שרימפס',             array['חסילונים'],                     'meat', 'חבילה', '🦐', false),

  -- frozen
  (null, 'אפונה קפואה',        array['אפונה'],                        'frozen', 'חבילה', '🫛', true),
  (null, 'תערובת ירקות קפואה', array['ירקות קפואים'],                 'frozen', 'חבילה', '🧊', true),
  (null, 'שעועית ירוקה קפואה', array['שעועית ירוקה'],                 'frozen', 'חבילה', '🫛', false),
  (null, 'תירס קפוא',          array[]::text[],                       'frozen', 'חבילה', '🌽', false),
  (null, 'צ׳יפס קפוא',         array['צ׳יפס'],                        'frozen', 'חבילה', '🍟', true),
  (null, 'מלאווח',             array['מלאוח'],                        'frozen', 'חבילה', '🫓', false),
  (null, 'ג׳חנון',             array['גחנון'],                        'frozen', 'חבילה', '🫓', false),
  (null, 'בצק עלים',           array['עלים קפוא'],                    'frozen', 'חבילה', '🥐', false),
  (null, 'שקדי מרק',           array[]::text[],                       'frozen', 'חבילה', '🍜', false),
  (null, 'גלידה וניל',         array['גלידה'],                        'frozen', 'יח׳', '🍦', false),
  (null, 'גלידה שוקולד',       array[]::text[],                       'frozen', 'יח׳', '🍦', false),
  (null, 'ארטיקים',            array['ארטיק'],                        'frozen', 'חבילה', '🍧', false),
  (null, 'בורקס קפוא',         array[]::text[],                       'frozen', 'חבילה', '🥟', false),
  (null, 'קרואסון קפוא',       array[]::text[],                       'frozen', 'חבילה', '🥐', false),
  (null, 'שניצל קפוא',         array[]::text[],                       'frozen', 'חבילה', '🍗', false),
  (null, 'פירות יער קפואים',   array['פירות יער'],                    'frozen', 'חבילה', '🫐', false),
  (null, 'קרפ קפוא',           array[]::text[],                       'frozen', 'חבילה', '🥞', false),
  (null, 'רביולי קפוא',        array['רביולי'],                       'frozen', 'חבילה', '🥟', false),

  -- canned
  (null, 'טונה בשמן',          array['טונה'],                         'canned', 'יח׳', '🐟', true),
  (null, 'טונה במים',          array[]::text[],                       'canned', 'יח׳', '🐟', false),
  (null, 'תירס משומר',         array['תירס'],                         'canned', 'יח׳', '🌽', true),
  (null, 'אפונה משומרת',       array[]::text[],                       'canned', 'יח׳', '🫛', false),
  (null, 'רסק עגבניות',        array['רסק'],                          'canned', 'יח׳', '🥫', true),
  (null, 'פסטת עגבניות',       array['עגבניות מרוסקות'],              'canned', 'יח׳', '🥫', true),
  (null, 'זיתים ירוקים',       array['זיתים'],                        'canned', 'יח׳', '🫒', true),
  (null, 'זיתים שחורים',       array[]::text[],                       'canned', 'יח׳', '🫒', false),
  (null, 'מלפפון חמוץ',        array['חמוצים','מלפפונים חמוצים'],     'canned', 'צנצנת', '🥒', true),
  (null, 'כרוב כבוש',          array[]::text[],                       'canned', 'צנצנת', '🥬', false),
  (null, 'חומוס גרגירים',      array['גרגירי חומוס'],                 'canned', 'יח׳', '🥫', true),
  (null, 'שעועית לבנה',        array[]::text[],                       'canned', 'יח׳', '🥫', false),
  (null, 'סרדינים',            array[]::text[],                       'canned', 'יח׳', '🐟', false),
  (null, 'פטריות משומרות',     array[]::text[],                       'canned', 'יח׳', '🍄', false),
  (null, 'אננס בקופסה',        array['אננס'],                         'canned', 'יח׳', '🍍', false),
  (null, 'אפרסקים בקופסה',     array[]::text[],                       'canned', 'יח׳', '🍑', false),
  (null, 'חלבה',               array['חלווה'],                        'canned', 'יח׳', '🍬', false),
  (null, 'מרק עוף אבקה',       array['אבקת מרק'],                     'canned', 'יח׳', '🍜', true),
  (null, 'קופסת חמוצים מעורבים', array['חמוצים מעורבים'],             'canned', 'צנצנת', '🥒', false),
  (null, 'פלפל קלוי',          array[]::text[],                       'canned', 'צנצנת', '🫑', false),

  -- grains
  (null, 'אורז לבן',           array['אורז'],                         'grains', 'ק״ג', '🍚', true),
  (null, 'אורז בסמטי',         array['בסמטי'],                        'grains', 'ק״ג', '🍚', false),
  (null, 'אורז מלא',           array[]::text[],                       'grains', 'ק״ג', '🍚', false),
  (null, 'פסטה ספגטי',         array['ספגטי','פסטה'],                 'grains', 'חבילה', '🍝', true),
  (null, 'פסטה פנה',           array['פנה'],                          'grains', 'חבילה', '🍝', true),
  (null, 'פתיתים',             array['פתיתונים'],                     'grains', 'חבילה', '🍚', true),
  (null, 'קוסקוס',             array['קוסקוס דק'],                    'grains', 'חבילה', '🍚', true),
  (null, 'בורגול',             array[]::text[],                       'grains', 'ק״ג', '🌾', false),
  (null, 'קינואה',             array[]::text[],                       'grains', 'חבילה', '🌾', false),
  (null, 'עדשים כתומות',       array['עדשים'],                        'grains', 'ק״ג', '🫘', true),
  (null, 'עדשים שחורות',       array[]::text[],                       'grains', 'ק״ג', '🫘', false),
  (null, 'שעועית יבשה',        array[]::text[],                       'grains', 'ק״ג', '🫘', false),
  (null, 'גריסים',             array[]::text[],                       'grains', 'ק״ג', '🌾', false),
  (null, 'קמח לבן',            array['קמח'],                          'grains', 'ק״ג', '🌾', true),
  (null, 'קמח מלא',            array[]::text[],                       'grains', 'ק״ג', '🌾', false),
  (null, 'סולת',               array[]::text[],                       'grains', 'ק״ג', '🌾', false),
  (null, 'שיבולת שועל',        array['קוואקר','שיבולת'],              'grains', 'חבילה', '🥣', true),
  (null, 'קורנפלקס',           array['דגני בוקר'],                    'grains', 'חבילה', '🥣', true),
  (null, 'גרנולה',             array[]::text[],                       'grains', 'חבילה', '🥣', false),
  (null, 'פירורי לחם',         array['פירורים','בצק לציפוי'],         'grains', 'חבילה', '🍞', true),

  -- condiments
  (null, 'שמן זית',            array['שמן זית כתית'],                 'condiments', 'ליטר', '🫒', true),
  (null, 'שמן קנולה',          array['שמן'],                          'condiments', 'ליטר', '🛢️', true),
  (null, 'חומץ',               array['חומץ בלסמי','חומץ יין'],        'condiments', 'יח׳', '🧴', false),
  (null, 'מיונז',              array['מיונז חצי'],                    'condiments', 'יח׳', '🥫', true),
  (null, 'קטשופ',              array['רוטב עגבניות'],                 'condiments', 'יח׳', '🥫', true),
  (null, 'חרדל',               array[]::text[],                       'condiments', 'יח׳', '🥫', false),
  (null, 'טחינה גולמית',       array['טחינה'],                        'condiments', 'יח׳', '🥫', true),
  (null, 'חומוס מוכן',         array['חומוס'],                        'condiments', 'יח׳', '🥫', true),
  (null, 'חריף',               array['סחוג','רוטב חריף'],             'condiments', 'יח׳', '🌶️', false),
  (null, 'סויה',               array['רוטב סויה'],                    'condiments', 'יח׳', '🍶', false),
  (null, 'סילאן',              array['דבש תמרים'],                    'condiments', 'יח׳', '🍯', false),
  (null, 'מלח',                array['מלח שולחן'],                    'condiments', 'ק״ג', '🧂', true),
  (null, 'פלפל שחור',          array['פלפל גרוס'],                    'condiments', 'יח׳', '🧂', true),
  (null, 'פפריקה',             array['פפריקה מתוקה'],                 'condiments', 'יח׳', '🌶️', true),
  (null, 'כמון',               array[]::text[],                       'condiments', 'יח׳', '🧂', true),
  (null, 'כורכום',             array[]::text[],                       'condiments', 'יח׳', '🧂', false),
  (null, 'קינמון',             array[]::text[],                       'condiments', 'יח׳', '🧂', false),
  (null, 'אורגנו',             array[]::text[],                       'condiments', 'יח׳', '🌿', false),
  (null, 'זעתר',               array[]::text[],                       'condiments', 'יח׳', '🌿', false),
  (null, 'בהרט',               array[]::text[],                       'condiments', 'יח׳', '🧂', false),
  (null, 'אבקת שום',           array[]::text[],                       'condiments', 'יח׳', '🧄', false),
  (null, 'שמרים יבשים',        array['שמרים'],                        'condiments', 'יח׳', '🧫', false),
  (null, 'אבקת אפייה',         array['בייקינג פאודר'],                'condiments', 'יח׳', '🧫', false),
  (null, 'סודה לשתייה',        array['סודה לאפייה'],                  'condiments', 'יח׳', '🧫', false),
  (null, 'תמצית וניל',         array['וניל'],                         'condiments', 'יח׳', '🧴', false),

  -- coffee
  (null, 'קפה נמס',            array['קפה עלית','נמס'],               'coffee', 'יח׳', '☕', true),
  (null, 'קפה טורקי',          array['קפה שחור'],                     'coffee', 'יח׳', '☕', true),
  (null, 'קפסולות קפה',        array['קפסולות'],                      'coffee', 'חבילה', '☕', false),
  (null, 'קפה שחור טחון',      array['קפה טחון'],                     'coffee', 'יח׳', '☕', false),
  (null, 'תה שחור',            array['תה'],                           'coffee', 'חבילה', '🍵', true),
  (null, 'תה ירוק',            array[]::text[],                       'coffee', 'חבילה', '🍵', false),
  (null, 'תה נענע',            array[]::text[],                       'coffee', 'חבילה', '🍵', false),
  (null, 'תה צמחים',           array['אינפוזיה'],                     'coffee', 'חבילה', '🍵', false),
  (null, 'סוכר',               array['סוכר לבן'],                     'coffee', 'ק״ג', '🍚', true),
  (null, 'סוכר חום',           array[]::text[],                       'coffee', 'ק״ג', '🍚', false),
  (null, 'סוכרזית',            array['תחליף סוכר'],                   'coffee', 'יח׳', '🍚', false),
  (null, 'שוקולד למשקה',       array['אבקת שוקו'],                    'coffee', 'יח׳', '🍫', false),
  (null, 'ממרח שוקולד',        array['נוטלה','שחור לבן'],             'coffee', 'יח׳', '🍫', true),
  (null, 'ריבת תות',           array['ריבה'],                         'coffee', 'צנצנת', '🍓', false),
  (null, 'ריבת משמש',          array[]::text[],                       'coffee', 'צנצנת', '🍑', false),
  (null, 'דבש',                array['דבש דבורים'],                   'coffee', 'יח׳', '🍯', true),
  (null, 'חמאת בוטנים',        array['ממרח בוטנים'],                  'coffee', 'צנצנת', '🥜', false),
  (null, 'ממרח שוקולד לבן',    array[]::text[],                       'coffee', 'יח׳', '🍫', false),

  -- snacks
  (null, 'במבה',               array['במבה אסם'],                     'snacks', 'חבילה', '🥜', true),
  (null, 'ביסלי',              array['ביסלי גריל'],                   'snacks', 'חבילה', '🥨', true),
  (null, 'אפרופו',             array[]::text[],                       'snacks', 'חבילה', '🥨', false),
  (null, 'דוריטוס',            array[]::text[],                       'snacks', 'חבילה', '🌮', false),
  (null, 'תפוצ׳יפס',           array['צ׳יפס בשקית'],                  'snacks', 'חבילה', '🥔', false),
  (null, 'פופקורן',            array[]::text[],                       'snacks', 'חבילה', '🍿', false),
  (null, 'שוקולד פרה',         array['שוקולד חלב'],                   'snacks', 'יח׳', '🍫', true),
  (null, 'שוקולד מריר',        array[]::text[],                       'snacks', 'יח׳', '🍫', false),
  (null, 'שוקולד עם אגוזים',   array[]::text[],                       'snacks', 'יח׳', '🍫', false),
  (null, 'קליק',               array[]::text[],                       'snacks', 'חבילה', '🍫', false),
  (null, 'פסק זמן',            array[]::text[],                       'snacks', 'חבילה', '🍫', false),
  (null, 'עוגיות שוקולד צ׳יפס', array['עוגיות'],                      'snacks', 'חבילה', '🍪', true),
  (null, 'וופלים',             array['וופל'],                         'snacks', 'חבילה', '🧇', false),
  (null, 'סוכריות גומי',       array['סוכריות'],                      'snacks', 'חבילה', '🍬', false),
  (null, 'מסטיק',              array[]::text[],                       'snacks', 'חבילה', '🍬', false),
  (null, 'חטיפי אנרגיה',       array['חטיף חלבון'],                   'snacks', 'חבילה', '🍫', false),
  (null, 'בוטנים',             array['בוטנים קלויים'],                'snacks', 'ק״ג', '🥜', false),
  (null, 'שקדים',              array[]::text[],                       'snacks', 'ק״ג', '🌰', false),
  (null, 'אגוזי מלך',          array['אגוזים'],                       'snacks', 'ק״ג', '🌰', false),
  (null, 'קשיו',               array[]::text[],                       'snacks', 'ק״ג', '🌰', false),
  (null, 'פיסטוקים',           array['פיסטוק'],                       'snacks', 'ק״ג', '🌰', false),
  (null, 'גרעיני חמנייה',      array['גרעינים'],                      'snacks', 'ק״ג', '🌻', false),
  (null, 'צימוקים',            array[]::text[],                       'snacks', 'חבילה', '🍇', false),
  (null, 'פירות יבשים',        array[]::text[],                       'snacks', 'חבילה', '🍑', false),
  (null, 'חטיף אורז',          array[]::text[],                       'snacks', 'חבילה', '🍘', false),

  -- drinks
  (null, 'מים מינרלים',        array['מים','בקבוק מים'],              'drinks', 'מארז', '💧', true),
  (null, 'סודה',               array['מים בגז'],                      'drinks', 'מארז', '💧', false),
  (null, 'קולה',               array['קוקה קולה'],                    'drinks', 'מארז', '🥤', false),
  (null, 'קולה זירו',          array['זירו'],                         'drinks', 'מארז', '🥤', false),
  (null, 'ספרייט',             array[]::text[],                       'drinks', 'מארז', '🥤', false),
  (null, 'פאנטה',              array[]::text[],                       'drinks', 'מארז', '🥤', false),
  (null, 'מיץ תפוזים',         array['מיץ'],                          'drinks', 'ליטר', '🧃', true),
  (null, 'מיץ תפוחים',         array[]::text[],                       'drinks', 'ליטר', '🧃', false),
  (null, 'מיץ ענבים',          array[]::text[],                       'drinks', 'ליטר', '🧃', false),
  (null, 'מיץ אשכוליות',       array[]::text[],                       'drinks', 'ליטר', '🧃', false),
  (null, 'לימונענע',           array['לימונדה'],                      'drinks', 'ליטר', '🍹', false),
  (null, 'תרכיז פטל',          array['פטל','תרכיז'],                  'drinks', 'יח׳', '🧃', false),
  (null, 'בירה',               array['בירות'],                        'drinks', 'מארז', '🍺', false),
  (null, 'יין אדום',           array['יין'],                          'drinks', 'בקבוק', '🍷', false),
  (null, 'יין לבן',            array[]::text[],                       'drinks', 'בקבוק', '🍷', false),
  (null, 'ערק',                array[]::text[],                       'drinks', 'בקבוק', '🥃', false),
  (null, 'וודקה',              array[]::text[],                       'drinks', 'בקבוק', '🥃', false),
  (null, 'משקה איזוטוני',      array['משקה ספורט'],                   'drinks', 'יח׳', '🥤', false),
  (null, 'משקה אנרגיה',        array[]::text[],                       'drinks', 'יח׳', '🥤', false),
  (null, 'שתייה קלה בפחיות',   array['פחיות'],                        'drinks', 'מארז', '🥤', false),
  (null, 'מי סודה בסיפון',     array['גזוז'],                         'drinks', 'יח׳', '💧', false),
  (null, 'קפה קר',             array['אייס קפה'],                     'drinks', 'יח׳', '🧋', false),

  -- baby
  (null, 'חיתולים',            array['חיתול','טיטולים'],              'baby', 'חבילה', '🍼', true),
  (null, 'מגבונים',            array['מגבונים לחים'],                 'baby', 'חבילה', '🧻', true),
  (null, 'תרכובת מזון לתינוקות', array['פורמולה','מטרנה'],            'baby', 'יח׳', '🍼', false),
  (null, 'דגני תינוקות',       array['דגנים לתינוק'],                 'baby', 'יח׳', '🥣', false),
  (null, 'מחית פירות',         array['מחית'],                         'baby', 'חבילה', '🍎', false),
  (null, 'משחת החתלה',         array['משחה לתינוק'],                  'baby', 'יח׳', '🧴', false),
  (null, 'שמפו לתינוק',        array[]::text[],                       'baby', 'יח׳', '🧴', false),
  (null, 'סבון לתינוק',        array[]::text[],                       'baby', 'יח׳', '🧼', false),
  (null, 'בקבוק לתינוק',       array[]::text[],                       'baby', 'יח׳', '🍼', false),
  (null, 'מוצץ',               array['מוצצים'],                       'baby', 'יח׳', '🍼', false),
  (null, 'חטיף תינוקות',       array['חטיף אורז לתינוק'],             'baby', 'חבילה', '🍘', false),
  (null, 'שקיות להנקה',        array['שקיות אחסון חלב'],              'baby', 'חבילה', '🍼', false),

  -- cleaning
  (null, 'סבון כלים',          array['נוזל כלים','פיירי'],            'cleaning', 'יח׳', '🧼', true),
  (null, 'אקונומיקה',          array['סנו אקונומיקה'],                'cleaning', 'יח׳', '🧴', true),
  (null, 'מטליות',             array['מטלית','סמרטוט'],               'cleaning', 'חבילה', '🧽', true),
  (null, 'ספוגים',             array['ספוג'],                         'cleaning', 'חבילה', '🧽', true),
  (null, 'אבקת כביסה',         array['אבקה לכביסה'],                  'cleaning', 'יח׳', '🧺', true),
  (null, 'ג׳ל כביסה',          array['נוזל כביסה'],                   'cleaning', 'יח׳', '🧺', false),
  (null, 'מרכך כביסה',         array['מרכך'],                         'cleaning', 'יח׳', '🧺', true),
  (null, 'מסיר כתמים',         array['ואניש'],                        'cleaning', 'יח׳', '🧴', false),
  (null, 'מטהר אוויר',         array['ספריי ריח'],                    'cleaning', 'יח׳', '🌬️', false),
  (null, 'נוזל לניקוי רצפות',  array['סבון רצפה'],                    'cleaning', 'יח׳', '🧴', true),
  (null, 'חומר לניקוי חלונות', array['מנקה חלונות'],                  'cleaning', 'יח׳', '🪟', false),
  (null, 'מנקה אסלות',         array['ג׳ל אסלה'],                     'cleaning', 'יח׳', '🚽', true),
  (null, 'כפכפי ניקוי',        array['כפפות לניקוי','כפפות'],         'cleaning', 'חבילה', '🧤', false),
  (null, 'שקיות אשפה',         array['שקיות זבל'],                    'cleaning', 'חבילה', '🗑️', true),
  (null, 'טבליות למדיח',       array['טבליות מדיח'],                  'cleaning', 'חבילה', '🍽️', true),
  (null, 'מלח למדיח',          array[]::text[],                       'cleaning', 'יח׳', '🧂', false),
  (null, 'מבריק למדיח',        array[]::text[],                       'cleaning', 'יח׳', '✨', false),
  (null, 'אבקת ניקוי כללית',   array[]::text[],                       'cleaning', 'יח׳', '🧴', false),
  (null, 'מסיר אבנית',         array[]::text[],                       'cleaning', 'יח׳', '🧴', false),
  (null, 'מברשת אסלה',         array[]::text[],                       'cleaning', 'יח׳', '🚽', false),
  (null, 'מגב',                array['מגב רצפה'],                     'cleaning', 'יח׳', '🧹', false),
  (null, 'מטאטא',              array[]::text[],                       'cleaning', 'יח׳', '🧹', false),

  -- pharma
  (null, 'נייר טואלט',         array['טואלט','גליל'],                 'pharma', 'חבילה', '🧻', true),
  (null, 'שמפו',               array['שמפו לשיער'],                   'pharma', 'יח׳', '🧴', true),
  (null, 'מרכך לשיער',         array['קונדישינר'],                    'pharma', 'יח׳', '🧴', false),
  (null, 'סבון גוף',           array['אל סבון','ג׳ל רחצה'],           'pharma', 'יח׳', '🧼', true),
  (null, 'סבון ידיים',         array['סבון'],                         'pharma', 'יח׳', '🧼', true),
  (null, 'משחת שיניים',        array['משחת שינים','קולגייט'],         'pharma', 'יח׳', '🦷', true),
  (null, 'מברשת שיניים',       array['מברשת שינים'],                  'pharma', 'יח׳', '🦷', false),
  (null, 'חוט דנטלי',          array[]::text[],                       'pharma', 'יח׳', '🦷', false),
  (null, 'מי פה',              array['מי פה לשטיפה'],                 'pharma', 'יח׳', '🦷', false),
  (null, 'דאודורנט',           array['דאו'],                          'pharma', 'יח׳', '🧴', true),
  (null, 'סכיני גילוח',        array['סכין גילוח','ג׳ילט'],           'pharma', 'חבילה', '🪒', false),
  (null, 'קצף גילוח',          array[]::text[],                       'pharma', 'יח׳', '🧴', false),
  (null, 'תחבושות היגייניות',  array['תחבושות','אולוויז'],            'pharma', 'חבילה', '🩹', true),
  (null, 'טמפונים',            array[]::text[],                       'pharma', 'חבילה', '🩹', false),
  (null, 'פלסטרים',            array['פלסטר','באנד אייד'],            'pharma', 'חבילה', '🩹', false),
  (null, 'אקמול',              array['פרצטמול'],                      'pharma', 'חבילה', '💊', true),
  (null, 'אדוויל',             array['נורופן','איבופרופן'],           'pharma', 'חבילה', '💊', false),
  (null, 'ויטמין D',           array['ויטמין די'],                    'pharma', 'יח׳', '💊', false),
  (null, 'קרם הגנה',           array['מסטיק שמש','קרם שיזוף'],        'pharma', 'יח׳', '🧴', false),
  (null, 'קרם גוף',            array['בודי לושן'],                    'pharma', 'יח׳', '🧴', false),
  (null, 'מגבונים לחים',       array['מגבונים לפנים'],                'pharma', 'חבילה', '🧻', false),
  (null, 'צמר גפן',            array['אוזניות צמר גפן'],              'pharma', 'חבילה', '🧻', false),

  -- household
  (null, 'מגבות נייר',         array['נייר מגבת','טישו מטבח'],        'household', 'חבילה', '🧻', true),
  (null, 'ממחטות נייר',        array['טישו','ממחטות'],                'household', 'חבילה', '🧻', true),
  (null, 'נייר אפייה',         array[]::text[],                       'household', 'יח׳', '📄', true),
  (null, 'נייר כסף',           array['אלומיניום'],                    'household', 'יח׳', '📄', true),
  (null, 'ניילון נצמד',        array['סטרץ׳'],                        'household', 'יח׳', '📄', false),
  (null, 'שקיות ניילון',       array['שקיות'],                        'household', 'חבילה', '🛍️', false),
  (null, 'צלחות חד פעמי',      array['צלחות'],                        'household', 'חבילה', '🍽️', false),
  (null, 'כוסות חד פעמי',      array['כוסות'],                        'household', 'חבילה', '🥤', false),
  (null, 'סכום חד פעמי',       array['סכום פלסטיק'],                  'household', 'חבילה', '🍴', false),
  (null, 'מפיות',              array['מפיות נייר'],                   'household', 'חבילה', '🧻', true),
  (null, 'נרות שבת',           array['נרות'],                         'household', 'חבילה', '🕯️', false),
  (null, 'גפרורים',            array['מצית'],                         'household', 'יח׳', '🔥', false),
  (null, 'סוללות AA',          array['סוללות','בטריות'],              'household', 'חבילה', '🔋', false),
  (null, 'נורות',              array['נורה','לד'],                    'household', 'יח׳', '💡', false),
  (null, 'תבניות אלומיניום',   array['תבנית חד פעמית'],               'household', 'חבילה', '🍱', false),
  (null, 'שקיות אחסון',        array['שקיות זיפ'],                    'household', 'חבילה', '🛍️', false),
  (null, 'קיסמים',             array[]::text[],                       'household', 'חבילה', '🍢', false),
  (null, 'קשיות',              array[]::text[],                       'household', 'חבילה', '🥤', false),

  -- pets
  (null, 'אוכל לכלב',          array['מזון לכלבים','אוכל כלבים'],     'pets', 'ק״ג', '🐕', true),
  (null, 'אוכל לחתול',         array['מזון לחתולים'],                 'pets', 'ק״ג', '🐈', true),
  (null, 'חול לחתולים',        array['חול חתולים'],                   'pets', 'חבילה', '🐈', true),
  (null, 'שימורים לחתול',      array[]::text[],                       'pets', 'יח׳', '🐈', false),
  (null, 'שימורים לכלב',       array[]::text[],                       'pets', 'יח׳', '🐕', false),
  (null, 'חטיפים לכלב',        array['עצם לכלב'],                     'pets', 'חבילה', '🦴', false),
  (null, 'שקיות לאיסוף צרכים', array['שקיות לכלב'],                   'pets', 'חבילה', '🐕', false),
  (null, 'מזון לדגים',         array[]::text[],                       'pets', 'יח׳', '🐠', false),
  (null, 'מזון לתוכים',        array['גרעינים לתוכי'],                'pets', 'חבילה', '🦜', false),
  (null, 'צעצוע לחיה',         array['צעצוע לכלב'],                   'pets', 'יח׳', '🧸', false),

  -- other
  (null, 'קרח',                array['שקית קרח'],                     'other', 'חבילה', '🧊', false),
  (null, 'פרחים',              array['זר פרחים'],                     'other', 'יח׳', '💐', false),
  (null, 'כרטיס ברכה',         array[]::text[],                       'other', 'יח׳', '💌', false),
  (null, 'נייר עטיפה',         array[]::text[],                       'other', 'יח׳', '🎁', false),
  (null, 'בלונים',             array['בלון'],                         'other', 'חבילה', '🎈', false),
  (null, 'עיתון',              array[]::text[],                       'other', 'יח׳', '📰', false),
  (null, 'מטריה',              array[]::text[],                       'other', 'יח׳', '☂️', false),
  (null, 'גרביים',             array['גרב'],                          'other', 'חבילה', '🧦', false)
on conflict do nothing;
